export const siteName = "Neverland"
export const HOME_ROUTE = "/"
export const TICKET_ROUTE = "/ticket"
export const ADMIN_ROUTE = "/admin"
export const USERS_ROUTE = "/users"
export const ORG_ROUTE = "/orgs"
export const STUDENTS_ROUTE = "/students"
export const PERSONALSTUDENTS_ROUTE = "/personalstudents/:id"
export const PERSONALTICKET_ROUTE = "/personalticket/:id"
export const CREATESTUDENT_ROUTE = "/createstudentpage/:id"
export const PERSONALUSER_ROUTE = "/personalusers/:id"
export const PROFILE_ROUTE = "/profile"
export const TICKETCREATE_ROUTE = "/create/ticket"
export const USERCREATE_ROUTE = "/create/user"
export const STATISTIC_ROUTE = "/stat"
export const ORGCREATE_ROUTE = "/create/org"
export const ORGPROFILEPAGE_ROUTE = "/orgs/:id"

//backend
export const BACKEND_URL = "http://localhost:5000"