export const siteName = "Neverland"
export const HOME_ROUTE = "/"
export const TICKET_ROUTE = "/ticket"
export const USERS_ROUTE = "/users"
export const ORG_ROUTE = "/orgs"
export const STUDENTS_ROUTE = "/students"